### PR TITLE
wrong font family/size

### PR DESCRIPTION
**Pull request by janat08**

### CODE REVIEW

**Comment by lenny1882** [comment]
@janat08 What OS are you running? I've done a clean install of WebStorm on Ubuntu Gnome 17.04, and I'm seeing DejaVu as the default. Could well be that the font family changes based on the system - if so, I think it'd be better to remove the font options altogether, rather than setting specific font sizes and families.

**Comment by janat08** [comment]
u mean a clean install of VSC? I thought setting VSC's font is appropriate.

**Comment by lenny1882** [comment]
Sorry for the delay in responding. You're right, it should have been a clean VSCode install and not Webstorm.

I'm going to spin up a few clean VMs and see what the fonts come out as, as I believe that VSCode will go off system default. My question to you still stands: what OS are you running?

**Comment by janat08** [comment]
windows 10

**Comment by janat08** [comment]
with defaults of: 
```
  "editor.fontFamily": "Consolas, 'Courier New', monospace",

  // Enables/Disables font ligatures.
  "editor.fontLigatures": false,

  // Controls the font size in pixels.
  "editor.fontSize": 14,

  // Controls the font weight.
  "editor.fontWeight": "normal",
```

**Comment by lenny1882** [comment]
Cool, thanks.

**Comment by lenny1882** [comment]
An update: I've created clean VMs of Ubuntu 18.04, OSX El Capitan, Windows 7, and Windows 10, and checked the default fonts for both VSC and WS.

**VSCode**
OSX: _Menlo, Monaco, 'Courier New', monospace_, 12
Ubuntu:  _'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'_, 14
Win7: _Consolas, 'Courier New', monospace_, 14
Win10: _Consolas, 'Courier New', monospace_, 14

**WebStorm**
OSX: _Menlo_, 12
Ubuntu: _DejaVu Sans Mono_, 12
Win7: _Monospaced_, 12
Win10: _Monospaced_, 12

I'm going to decline this PR, as the change isn't suitable for all platforms. However, you are correct that the current version needs changes, so thanks for flagging it. I've got a bit of time over the next few days, so I'll have a look into whether WS will accept a colourings file without editor and console font settings.

**Comment by lenny1882** [comment]
@janat08 We're in luck - WS does not require the font settings in the colourings file! Whilst this will not directly set the VSC fonts in WS, it does mean that the Ubuntu fonts won't be forced over the WebStorm's default font choice in Windows.

I've removed the font settings, confirmed on my own machine, and merged into master.

**Pull request closed without merging**
